M48
; DRILL file {KiCad (6.0.0)} date Sun Feb  6 12:12:23 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-06T12:12:23-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.302
%
G90
G05
T1
X107.861Y-79.604
X107.861Y-130.404
X189.141Y-79.604
X189.141Y-130.404
T0
M30
